DROP TABLE IF EXISTS student;
DROP SEQUENCE IF EXISTS SEQUENCE_GENERATOR;

CREATE SEQUENCE IF NOT EXISTS SEQUENCE_GENERATOR START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS student (
    id INT DEFAULT NEXT VALUE FOR SEQUENCE_GENERATOR PRIMARY KEY,
    name VARCHAR(40),
    age INT
);
